// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent as parsed from a single corpus `.md` file. `body` is the
 * markdown persona and is omitted/empty in list views (`corpus_list`)
 * to keep payloads small; `corpus_get` returns it populated.
 */
export type Agent = { 
/**
 * Filename without `.md`, e.g. `"frontend-developer"`.
 */
slug: string, 
/**
 * Frontmatter `name`.
 */
name: string, 
/**
 * Frontmatter `description`.
 */
description: string, 
/**
 * Parent directory, e.g. `"engineering"`.
 */
category: string, 
/**
 * Frontmatter `emoji`.
 */
emoji: string | null, 
/**
 * Frontmatter `color` (named or hex).
 */
color: string | null, 
/**
 * Frontmatter `vibe`.
 */
vibe: string | null, 
/**
 * Markdown body (persona) — lazy/optional in list views.
 */
body: string, };

/**
 * Result of `agent_diff` — what's on disk now vs the canonical render the app
 * would write. Powers "review before Update": the UI can show the user exactly
 * what an Update/Restore would change before any file is touched.
 */
export type AgentDiff = { slug: string, tool: string, projectPath: string | null, dest: string, 
/**
 * Current on-disk contents (None if the file is missing).
 */
onDisk: string | null, 
/**
 * The canonical render the app would write.
 */
proposed: string, 
/**
 * Whether the two differ (false ⇒ Update is a no-op).
 */
differs: boolean, };

/**
 * One entry in the per-app `backups/index.json` ledger — a snapshot of an
 * agent file taken just before a destructive install/update wrote a new
 * render to the same path. The list is what the rollback UI shows and
 * `backup_restore` resolves back to a `dest`.
 *
 * `dest` is the absolute path the backup will be restored to; `filename`
 * is the on-disk name inside `app_data_dir/backups/`. `created_at` is
 * RFC3339 (matches `InstallRecord::installed_at`).
 */
export type BackupEntry = { filename: string, dest: string, tool: string, slug: string, createdAt: string, size: bigint, };

/**
 * A catalog directory discovered on disk (for the first-run / Settings picker).
 */
export type CatalogCandidate = { 
/**
 * Absolute path to the candidate catalog root.
 */
path: string, 
/**
 * `"managed"` for `~/.agency-agents`, else `"userClone"`.
 */
kind: string, 
/**
 * Whether it's a git checkout (has `.git`) — drives pull strategy.
 */
hasGit: boolean, 
/**
 * Quick agent count (top-level `.md` across discovered categories).
 */
agentCount: number, };

/**
 * Result of `catalog_detect` — what the app found, plus whether `git` is on
 * PATH (so the UI can explain clone vs snapshot provisioning).
 */
export type CatalogDetection = { gitAvailable: boolean, 
/**
 * True when a filesystem scan of common dev roots was performed (the
 * "Find Agency Agents" button), vs the cheap `~/.agency-agents`-only check.
 */
scanned: boolean, candidates: Array<CatalogCandidate>, };

/**
 * Where the active agent catalog lives on disk. The whole app reads/writes the
 * resolved root, so this is the one knob that says "be a respectful frontend
 * over the user's clone" vs "manage our own copy." Persisted to
 * `state/catalog.json`. Serialized tagged on `kind` so the TS side is a clean
 * discriminated union.
 */
export type CatalogSource = { "kind": "bundled" } | { "kind": "managed", path: string, } | { "kind": "userClone", path: string, manage: boolean, };

/**
 * Live status of the active catalog — source, git provenance, and freshness.
 * Powers the Settings → Catalog panel ("manage the repo": which commit, how
 * far behind, what GitHub repo). All git fields are `None`/0 for a non-git
 * (bundled snapshot) source.
 */
export type CatalogStatus = { source: CatalogSource, 
/**
 * Catalog root path (None for the bundled, app-data-internal source).
 */
root: string | null, isGit: boolean, branch: string | null, 
/**
 * Short commit SHA of HEAD.
 */
commit: string | null, lastCommitSubject: string | null, lastCommitDate: string | null, 
/**
 * Count of uncommitted working-tree changes.
 */
dirtyCount: number, 
/**
 * `origin` remote URL, if a git checkout.
 */
remoteUrl: string | null, 
/**
 * `owner/repo` parsed from the remote (for GitHub repo stats), if it's a
 * github.com remote.
 */
repoSlug: string | null, version: string, fetchedAt: string, agentCount: number, };

/**
 * Result of checking the active catalog for upstream updates — the "stats on
 * diffs" view. Git sources fetch + compare against the upstream branch.
 */
export type CatalogUpdateCheck = { isGit: boolean, 
/**
 * Commits the upstream branch has that we don't (how far behind).
 */
behind: number, 
/**
 * Commits we have that upstream doesn't (local work).
 */
ahead: number, 
/**
 * Files that would change on pull.
 */
changedFiles: number, 
/**
 * Human-readable `git diff --stat` of HEAD..upstream.
 */
diffstat: string, 
/**
 * True when already at the upstream tip (git) — no-op pull.
 */
upToDate: boolean, };

/**
 * One category for the Discover grid. `slug` is the corpus parent dir
 * (e.g. `"engineering"`); `icon` is a PascalCase Lucide icon name the
 * frontend resolves via its static icon map.
 */
export type Category = { slug: string, label: string, icon: string, 
/**
 * Brand color (hex) for the division, from the catalog metadata.
 */
color: string, count: number, };

/**
 * One row of `corpus-index.json`. The three split hashes let update
 * classification distinguish cosmetic (frontmatter-only) from
 * substantive (body) changes. Hash = SHA-256 lowercase hex of UTF-8
 * bytes (contracts.md §E).
 */
export type CorpusEntry = { slug: string, name: string, category: string, emoji: string | null, color: string | null, vibe: string | null, description: string, 
/**
 * SHA-256 of the full canonical `.md`.
 */
sourceHash: string, 
/**
 * SHA-256 of the frontmatter block.
 */
frontmatterHash: string, 
/**
 * SHA-256 of the body.
 */
bodyHash: string, };

/**
 * Top-level metadata for the maintained corpus copy.
 */
export type CorpusMeta = { version: string, commit: string | null, fetchedAt: string, count: number, };

/**
 * One row of `installs.json` — the ledger of local install actions.
 * `source_hash` records the corpus version installed from;
 * `rendered_hash` is the SHA-256 of the exact bytes written after
 * per-tool conversion, used by reconciliation to classify state.
 */
export type InstallRecord = { slug: string, tool: string, scope: Scope, projectPath: string | null, 
/**
 * Absolute path written.
 */
dest: string, sourceHash: string, 
/**
 * SHA-256 of the agent body at install time. Lets reconciliation label an
 * available update cosmetic (body unchanged) vs substantive. `#[serde(default)]`
 * so ledgers written before this field still parse (older rows get "").
 */
bodyHash: string, renderedHash: string, installedAt: string, corpusVersion: string, };

/**
 * The five reconciliation states (like a package manager's installed /
 * outdated states). See systemPatterns.md §4 for the disk ↔ ledger ↔ corpus
 * test that classifies each on-disk agent file.
 */
export type InstallState = "current" | "outdated" | "modified" | "removed" | "foreign";

/**
 * Reconciled view-model for the Library — one on-disk agent file
 * resolved against the ledger and corpus-index. `update_kind` is
 * `Some(..)` only when `state == Outdated`.
 */
export type InstalledAgent = { slug: string, name: string, tool: string, scope: Scope, projectPath: string | null, dest: string, state: InstallState, updateKind: UpdateKind | null, 
/**
 * True when THIS app installed it (it's in the ledger); false when the
 * Foreign sweep found it on disk (e.g. a prior `install.sh` run). Lets the
 * UI distinguish "tracked by the app" from "present from other tools"
 * instead of claiming every recognized file as "installed by you".
 */
tracked: boolean, };

/**
 * One log file in the per-app `logs/` directory.
 */
export type LogFile = { name: string, size: bigint, createdAt: string, };

/**
 * A registered project directory for project-scoped installs. The app
 * keeps a Projects list so Library/Tools can show per-project
 * deployment; one agent in five projects = five tracked rows.
 */
export type ProjectInfo = { 
/**
 * Absolute project root path.
 */
path: string, 
/**
 * Display label (defaults to the directory name).
 */
label: string, 
/**
 * Count of agents installed into this project across all
 * project-scoped tools.
 */
installedCount: number, };

/**
 * Deployment scope. User-global tools write to fixed `~/…` dests;
 * project-scoped tools install into a tracked `project_path`.
 */
export type Scope = "user" | "project";

/**
 * View-model for the Tools section — a detected AI tool plus its
 * deployment surface.
 */
export type ToolInfo = { tool: string, label: string, detected: boolean, scope: Scope, userDest: string | null, installedCount: number, 
/**
 * Per-tool custom install base path the user configured (else `None` =
 * OS home). Detection + `user_dest` already reflect this base.
 */
customPath: string | null, };

/**
 * Best-effort detected version string for a tool, from probing `<bin>
 * --version`. `version` is `None` when the binary isn't on PATH, the probe
 * timed out, or the tool has no known version command.
 */
export type ToolVersion = { tool: string, version: string | null, };

/**
 * Whether an available update is cosmetic (frontmatter/metadata only,
 * `body_hash` unchanged) or substantive (prompt body changed).
 */
export type UpdateKind = "cosmetic" | "substantive";
