// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightCheck } from "./PreflightCheck";

/**
 * Result of a `preflight_hermes` call. The UI renders `checks` as a
 * list and uses `ready` for the banner headline.
 */
export type HermesPreflight = { 
/**
 * `true` iff no check has status `fail` (warns are fine).
 */
ready: boolean, checks: Array<PreflightCheck>, 
/**
 * ISO-8601 UTC timestamp of when the pre-flight ran.
 */
checkedAt: string, 
/**
 * Path the pre-flight probed for `home-writable` and
 * `install-target`, surfaced for the UI to display in the hint.
 */
home: string, };
