// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightStatus } from "./PreflightStatus";

/**
 * One row in the pre-flight checklist.
 */
export type PreflightCheck = { 
/**
 * Stable id, e.g. `"hermes-cli"`. Used as an i18n key and in tests.
 */
id: string, 
/**
 * Human-readable label, e.g. "Hermes CLI".
 */
label: string, status: PreflightStatus, 
/**
 * Concrete value (path, version, etc.). Empty string when not applicable.
 */
detail: string, 
/**
 * Optional fix-it suggestion, e.g. "Upgrade with `brew upgrade hermes`."
 */
remediation: string | null, 
/**
 * When `true`, a `fail` here means the install cannot succeed.
 */
blocking: boolean, };
